apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: netsil
  name: collector
  labels:
    app: netsil
    component: collector
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: netsil
        component: collector
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: collector
        image: netsil/collectors:stable-1.7.0
        command: ["/bin/bash","-c","while true ; do NETSIL_SP_HOST=$NETSIL_SERVICE_HOST /opt/netsil/collectors/start.sh ; echo Exiting, possibly to upgrade ; sleep 5 ; done"]
        securityContext:
          capabilities:
            add:
            - NET_RAW
            - NET_ADMIN
        env:
        #- name: NETSIL_SERVICE_HOST
        #  value: '<AOC address here>'
        #- name: NETSIL_ORGANIZATION_ID
        #  value: '<Your org id here>'
        - name: DEPLOY_ENV
          value: 'docker'
        - name: KUBERNETES
          value: "yes"
        - name: SD_BACKEND
          value: docker
        volumeMounts:
        - name: cgroup
          mountPath: /host/sys/fs/cgroup/
          readOnly: true
        - name: proc
          mountPath: /host/proc/
          readOnly: true
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: configmap-volume
          mountPath: /etc/netsil-dd-agent/conf.d/
        - name: configmap-auto_conf
          mountPath: /etc/netsil-dd-agent/auto_conf/
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup/
      - name: proc
        hostPath:
          path: /proc/
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: configmap-volume
        configMap:
          name: integrations
      - name: configmap-auto_conf
        configMap:
          name: auto_conf
